
import pytest
import uuid
from httpx import AsyncClient
from app.core.config import settings
from app.models.notification import Notification
from tests.utils import create_user_and_get_headers

@pytest.mark.asyncio
async def test_get_notifications(client: AsyncClient, session):
    user_data, headers = await create_user_and_get_headers(client)
    
    # We need user_id to seed notification
    # Fetch user
    resp = await client.get(f"{settings.API_V1_STR}/users/me", headers=headers)
    user_id = uuid.UUID(resp.json()["data"]["id"])
    
    # Create Notification
    notif = Notification(
        user_id=user_id,
        title="Test Notification",
        body="This is a test",
        type="info",
        is_read=False
    )
    session.add(notif)
    await session.commit()
    
    # Get Notifications
    resp = await client.get(
        f"{settings.API_V1_STR}/notifications/",
        headers=headers
    )
    
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert len(data) > 0
    assert data[0]["title"] == "Test Notification"

@pytest.mark.asyncio
async def test_mark_notification_read(client: AsyncClient, session):
    user_data, headers = await create_user_and_get_headers(client)
    resp = await client.get(f"{settings.API_V1_STR}/users/me", headers=headers)
    user_id = uuid.UUID(resp.json()["data"]["id"])
    
    notif = Notification(
        user_id=user_id,
        title="To be read",
        body="Read me",
        type="info",
        is_read=False
    )
    session.add(notif)
    await session.commit()
    await session.refresh(notif) # Refresh to get ID if needed, though we added it manually/with default?
    # notif.id is set by default_factory if not provided? No, it's set on add/commit if default factory.
    # Wait, in the test I passed `user_id` etc. `id` generated by DB or model default.
    # We need to refresh to make sure it's bound.
    
    # Mark as read
    # The endpoint is POST /notifications/{id}/read
    resp = await client.post(
        f"{settings.API_V1_STR}/notifications/{notif.id}/read",
        headers=headers
    )
    
    assert resp.status_code == 200
    assert resp.json()["message"] == "Marked as read"
    
    # Verify
    await session.refresh(notif)
    assert notif.is_read is True
