"""Add join_date to CircleMember

Revision ID: 6eb537c1ad4c
Revises: c72d39c2b06e
Create Date: 2025-12-26 22:53:00.679198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb537c1ad4c'
down_revision: Union[str, Sequence[str], None] = 'c72d39c2b06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circlemember', sa.Column('join_date', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circlemember', 'join_date')
    # ### end Alembic commands ###
