"""Add current_cycle to Circle

Revision ID: 7f57bef212da
Revises: 05108d4cf343
Create Date: 2025-12-31 20:35:15.382561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f57bef212da'
down_revision: Union[str, Sequence[str], None] = '05108d4cf343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle', sa.Column('current_cycle', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('circle', 'current_cycle')
    # ### end Alembic commands ###
