"""Add circle management fields

Revision ID: c72d39c2b06e
Revises: 702493780a6b
Create Date: 2025-12-26 22:42:28.264524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c72d39c2b06e'
down_revision: Union[str, Sequence[str], None] = '702493780a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('circle', sa.Column('target_members', sa.Integer(), nullable=True))
    op.add_column('circle', sa.Column('payout_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='fixed'))
    op.alter_column('circle', 'cycle_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circle', 'cycle_start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('circle', 'payout_preference')
    op.drop_column('circle', 'target_members')
    op.drop_column('circle', 'description')
    # ### end Alembic commands ###
