"""Add circle_id to Wallet and make user_id nullable

Revision ID: fb7db7a0d12e
Revises: 7f57bef212da
Create Date: 2025-12-31 21:19:22.492815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7db7a0d12e'
down_revision: Union[str, Sequence[str], None] = '7f57bef212da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('circle_id', sa.Uuid(), nullable=True))
    op.alter_column('wallet', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'wallet', 'circle', ['circle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.alter_column('wallet', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('wallet', 'circle_id')
    # ### end Alembic commands ###
