"""add transactions and update wallet

Revision ID: feb62caa3e4d
Revises: 6eb537c1ad4c
Create Date: 2025-12-26 23:46:41.997107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb62caa3e4d'
down_revision: Union[str, Sequence[str], None] = '6eb537c1ad4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circle', 'frequency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='circlefrequency'),
               existing_nullable=False,
               postgresql_using="frequency::circlefrequency")
    op.alter_column('circle', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', name='circlestatus'),
               existing_nullable=False,
               postgresql_using="status::circlestatus")
    op.alter_column('circle', 'payout_preference',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('FIXED', 'RANDOM', name='payoutpreference'),
               existing_nullable=False,
               existing_server_default=sa.text("'fixed'::character varying"),
               postgresql_using="payout_preference::payoutpreference")
    op.alter_column('circlemember', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('HOST', 'MEMBER', name='circlerole'),
               existing_nullable=False,
               postgresql_using="role::circlerole")
    op.alter_column('contribution', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'PAID', 'MISSED', 'OVERDUE', name='contributionstatus'),
               existing_nullable=False,
               postgresql_using="status::contributionstatus")
    op.alter_column('notification', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'ACTION_REQUIRED', name='notificationtype'),
               existing_nullable=False,
               postgresql_using="type::notificationtype")
    op.alter_column('notification', 'priority',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('HIGH', 'NORMAL', 'LOW', name='notificationpriority'),
               existing_nullable=False,
               postgresql_using="priority::notificationpriority")
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'USER', name='userrole'),
               existing_nullable=False,
               postgresql_using="role::userrole")
    op.alter_column('wallet', 'balance',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using="balance::bigint")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'balance',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('notification', 'priority',
               existing_type=sa.Enum('HIGH', 'NORMAL', 'LOW', name='notificationpriority'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('notification', 'type',
               existing_type=sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'ACTION_REQUIRED', name='notificationtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('contribution', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'MISSED', 'OVERDUE', name='contributionstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('circlemember', 'role',
               existing_type=sa.Enum('HOST', 'MEMBER', name='circlerole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('circle', 'payout_preference',
               existing_type=sa.Enum('FIXED', 'RANDOM', name='payoutpreference'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'fixed'::character varying"))
    op.alter_column('circle', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', name='circlestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('circle', 'frequency',
               existing_type=sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='circlefrequency'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
